//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xbim.Properties.Definitions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IFC4_COBie_Definition_files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IFC4_COBie_Definition_files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xbim.Properties.Definitions.IFC4_COBie_Definition_files", typeof(IFC4_COBie_Definition_files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySetDef xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ifdguid=&quot;682854416e034c9eb2e1fa6a85adfd78&quot; xsi:noNamespaceSchemaLocation=&quot;http://buildingSMART-tech.org/xml/psd/PSD_IFC4.xsd&quot;&gt;
        ///  &lt;IfcVersion version=&quot;IFC4&quot; /&gt;
        ///  &lt;Name&gt;COBie_ActionRequest&lt;/Name&gt;
        ///  &lt;Applicability&gt;PSET_OCCURRENCEDRIVEN&lt;/Applicability&gt;
        ///  &lt;ApplicableClasses&gt;
        ///    &lt;ClassName&gt;IfcActionRequest&lt;/ClassName&gt;
        ///  &lt;/ApplicableClasses&gt;
        ///  &lt;ApplicableTypeValue&gt;IfcAct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COBie_ActionRequest {
            get {
                return ResourceManager.GetString("COBie_ActionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySetDef xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ifdguid=&quot;c287f5f0094c446aa4be37ce4276d299&quot; xsi:noNamespaceSchemaLocation=&quot;http://buildingSMART-tech.org/xml/psd/PSD_IFC4.xsd&quot;&gt;
        ///  &lt;IfcVersion version=&quot;IFC4&quot; /&gt;
        ///  &lt;Name&gt;COBie_ConstructionProductResource&lt;/Name&gt;
        ///  &lt;Applicability&gt;PSET_OCCURRENCEDRIVEN&lt;/Applicability&gt;
        ///  &lt;ApplicableClasses&gt;
        ///    &lt;ClassName&gt;IfcConstructionProductResource&lt;/ClassName&gt;
        ///  &lt;/ApplicableClasses&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COBie_ConstructionProductResource {
            get {
                return ResourceManager.GetString("COBie_ConstructionProductResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySetDef xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ifdguid=&quot;85ef6c6b34cf49058eba131e9e99549e&quot; xsi:noNamespaceSchemaLocation=&quot;http://buildingSMART-tech.org/xml/psd/PSD_IFC4.xsd&quot;&gt;
        ///  &lt;IfcVersion version=&quot;IFC4&quot; /&gt;
        ///  &lt;Name&gt;COBie_ConstructionProductResourceType&lt;/Name&gt;
        ///  &lt;Applicability&gt;PSET_TYPEDRIVENONLY&lt;/Applicability&gt;
        ///  &lt;ApplicableClasses&gt;
        ///    &lt;ClassName&gt;IfcConstructionProductResourceType&lt;/ClassName&gt;
        ///  &lt;/ApplicableClass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COBie_ConstructionProductResourceType {
            get {
                return ResourceManager.GetString("COBie_ConstructionProductResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySetDef xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ifdguid=&quot;5579fe03628e464c9a8e2d049a1eb6bb&quot; xsi:noNamespaceSchemaLocation=&quot;http://buildingSMART-tech.org/xml/psd/PSD_IFC4.xsd&quot;&gt;
        ///  &lt;IfcVersion version=&quot;IFC4&quot; /&gt;
        ///  &lt;Name&gt;COBie_ElementType&lt;/Name&gt;
        ///  &lt;Applicability&gt;QTO_TYPEDRIVENONLY&lt;/Applicability&gt;
        ///  &lt;ApplicableClasses&gt;
        ///    &lt;ClassName&gt;IfcElementType&lt;/ClassName&gt;
        ///  &lt;/ApplicableClasses&gt;
        ///  &lt;ApplicableTypeValue&gt;IfcElementTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COBie_ElementType {
            get {
                return ResourceManager.GetString("COBie_ElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySetDef xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ifdguid=&quot;a42d038a72a64fc0b347723692c84984&quot; xsi:noNamespaceSchemaLocation=&quot;http://buildingSMART-tech.org/xml/psd/PSD_IFC4.xsd&quot;&gt;
        ///  &lt;IfcVersion version=&quot;IFC4&quot; /&gt;
        ///  &lt;Name&gt;COBie_Task&lt;/Name&gt;
        ///  &lt;Applicability&gt;PSET_OCCURRENCEDRIVEN&lt;/Applicability&gt;
        ///  &lt;ApplicableClasses&gt;
        ///    &lt;ClassName&gt;IfcTask&lt;/ClassName&gt;
        ///  &lt;/ApplicableClasses&gt;
        ///  &lt;ApplicableTypeValue&gt;IfcTask&lt;/ApplicableTypeV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COBie_Task {
            get {
                return ResourceManager.GetString("COBie_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySetDef xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ifdguid=&quot;d4ad2780d1bc11e1800000215ad4efdf&quot; xsi:noNamespaceSchemaLocation=&quot;http://buildingSMART-tech.org/xml/psd/PSD_IFC4.xsd&quot;&gt;
        ///  &lt;IfcVersion version=&quot;IFC4&quot; /&gt;
        ///  &lt;Name&gt;Pset_ActionRequest&lt;/Name&gt;
        ///  &lt;Definition&gt;An action request is a request for an action to fulfill a need.  HISTORY: IFC4: Removed RequestSourceType, RequestDescription, Status&lt;/Definition&gt;
        ///  &lt;Applicability [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pset_ActionRequest {
            get {
                return ResourceManager.GetString("Pset_ActionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySetDef xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ifdguid=&quot;46e93080d1ec11e1800000215ad4efdf&quot; xsi:noNamespaceSchemaLocation=&quot;http://buildingSMART-tech.org/xml/psd/PSD_IFC4.xsd&quot;&gt;
        ///  &lt;IfcVersion version=&quot;IFC4&quot; /&gt;
        ///  &lt;Name&gt;Pset_ManufacturerOccurrence&lt;/Name&gt;
        ///  &lt;Definition&gt;Defines properties of individual instances of manufactured products that may be given by the manufacturer.
        ///HISTORY: IFC 2x4: AssemblyPlace property added.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pset_ManufacturerOccurrence {
            get {
                return ResourceManager.GetString("Pset_ManufacturerOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySetDef xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ifdguid=&quot;71d38480d1ec11e1800000215ad4efdf&quot; xsi:noNamespaceSchemaLocation=&quot;http://buildingSMART-tech.org/xml/psd/PSD_IFC4.xsd&quot;&gt;
        ///  &lt;IfcVersion version=&quot;IFC4&quot; /&gt;
        ///  &lt;Name&gt;Pset_ManufacturerTypeInformation&lt;/Name&gt;
        ///  &lt;Definition&gt;Defines characteristics of types (ranges) of manufactured products that may be given by the manufacturer. Note that the term &apos;manufactured&apos; may also b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pset_ManufacturerTypeInformation {
            get {
                return ResourceManager.GetString("Pset_ManufacturerTypeInformation", resourceCulture);
            }
        }
    }
}
